// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skype.Client.UI.Data;

namespace Skype.Client.UI.Migrations
{
    [DbContext(typeof(FilterDbContext))]
    partial class FilterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Skype.Client.UI.Models.DestinationProfileVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FilterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilterId");

                    b.ToTable("DestinationProfiles");
                });

            modelBuilder.Entity("Skype.Client.UI.Models.Filter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("Skype.Client.UI.Models.SourceProfileVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FilterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilterId");

                    b.ToTable("SourceProfiles");
                });

            modelBuilder.Entity("Skype.Client.UI.Models.DestinationProfileVM", b =>
                {
                    b.HasOne("Skype.Client.UI.Models.Filter", "Filter")
                        .WithMany("DestinationChats")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");
                });

            modelBuilder.Entity("Skype.Client.UI.Models.SourceProfileVM", b =>
                {
                    b.HasOne("Skype.Client.UI.Models.Filter", "Filter")
                        .WithMany("SourceChats")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");
                });

            modelBuilder.Entity("Skype.Client.UI.Models.Filter", b =>
                {
                    b.Navigation("DestinationChats");

                    b.Navigation("SourceChats");
                });
#pragma warning restore 612, 618
        }
    }
}
